/* sitemap.xml: every page a search engine should index, in the site's
   canonical URL shape (`/about`, never `/about/`).

   Hand-listed rather than generated by an integration, because the list is
   short and the rules are the site's own: the 404 page is never listed, and
   /writing is listed only once the section has launched (before that it is
   built but carries noindex; see src/lib/writing.ts). Published posts are
   indexable, so they are listed whenever they exist.
   Add a new top-level page to STATIC_PAGES when you create it, listing the
   files its content comes from: <lastmod> is the newest commit among them.
   Home, About and Speaking print most of their copy from site.ts, so an edit
   there counts as a change to them; the essays carry their text inline. */
import type { APIRoute } from 'astro';
import { canonicalUrl } from '../lib/url';
import { TRACKS, getPosts, isWritingLive, postHref } from '../lib/writing';
import { lastModified } from '../lib/lastmod';

const SITE_DATA = 'src/data/site.ts';

const STATIC_PAGES: Record<string, string[]> = {
  '/': ['src/pages/index.astro', SITE_DATA],
  '/about': ['src/pages/about.astro', SITE_DATA],
  '/designed': ['src/pages/designed.astro'],
  '/confidence': ['src/pages/confidence.astro'],
  '/value': ['src/pages/value.astro'],
  '/speaking': ['src/pages/speaking.astro', SITE_DATA],
};

interface Entry {
  path: string;
  lastmod?: string;
}

export const GET: APIRoute = async ({ site }) => {
  const entries: Entry[] = Object.entries(STATIC_PAGES).map(([path, files]) => ({
    path,
    lastmod: lastModified(files),
  }));

  if (await isWritingLive()) {
    entries.push({ path: '/writing', lastmod: lastModified(['src/pages/writing.astro', 'src/content']) });
  }
  // A post states its own dates in frontmatter, which is what readers see.
  for (const track of TRACKS) {
    for (const post of await getPosts(track.key)) {
      const changed = post.data.updated ?? post.data.date;
      entries.push({ path: postHref(track.key, post), lastmod: changed.toISOString().slice(0, 10) });
    }
  }

  const urls = entries
    .map(({ path, lastmod }) => {
      const mod = lastmod ? `<lastmod>${lastmod}</lastmod>` : '';
      return `  <url><loc>${canonicalUrl(path, site!)}</loc>${mod}</url>`;
    })
    .join('\n');

  const body = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;

  return new Response(body, { headers: { 'Content-Type': 'application/xml; charset=utf-8' } });
};
