/* sitemap.xml: every page a search engine should index, in the site's
   canonical URL shape (`/about`, never `/about/`).

   Hand-listed rather than generated by an integration, because the list is
   short and the rules are the site's own: the 404 page is never listed, and
   /writing is listed only once the section has launched (before that it is
   built but carries noindex; see src/lib/writing.ts). Published posts are
   indexable, so they are listed whenever they exist.
   Add a new top-level page to STATIC_PAGES when you create it. */
import type { APIRoute } from 'astro';
import { canonicalUrl } from '../lib/url';
import { TRACKS, getPosts, isWritingLive, postHref } from '../lib/writing';

const STATIC_PAGES = ['/', '/about', '/designed', '/confidence', '/value', '/speaking'];

export const GET: APIRoute = async ({ site }) => {
  const paths = [...STATIC_PAGES];

  if (await isWritingLive()) paths.push('/writing');
  for (const track of TRACKS) {
    for (const post of await getPosts(track.key)) paths.push(postHref(track.key, post));
  }

  const urls = paths
    .map((p) => `  <url><loc>${canonicalUrl(p, site!)}</loc></url>`)
    .join('\n');

  const body = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
${urls}
</urlset>
`;

  return new Response(body, { headers: { 'Content-Type': 'application/xml; charset=utf-8' } });
};
